jdk: openjdk8
language: scala
scala:
  - 2.12.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - /opt/iv2

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  
  - sudo rm -fv /opt/ivy2/.sbt.ivy.lock
  - sudo find /opt/ivy2/cache -name "ivydata-*.properties" -print -delete

install:
  - sudo ./get_and_build_deps.sh >/dev/null
  - sudo chown $USER -R ~/.sbt
 
script:
  - sbt ++$TRAVIS_SCALA_VERSION test >/dev/null
